name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Run tests
      run: cargo test --workspace
    
    - name: Build plugin
      run: cargo build --bin protoc-gen-rn --release
    
    - name: Test basic example
      run: |
        cd examples/basic-resource
        # Update buf.gen.yaml to use local binary
        sed -i 's|- plugin: rn|- plugin: ../../target/release/protoc-gen-rn|g' buf.gen.yaml
        buf generate
        cargo check
        cargo run --example basic_usage
