name: Publish to crates.io

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      crate:
        description: 'Crate to publish (all, resource-types, resource-codegen, protoc-gen-rust-aip)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - resource-types
          - resource-codegen
          - protoc-gen-rust-aip

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish Crates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    # Verify everything builds before publishing
    - name: Run tests
      run: cargo test --workspace --verbose
    
    - name: Build all crates
      run: cargo build --workspace --release
    
    # Publish in dependency order
    - name: Publish resource-types
      if: ${{ github.event.inputs.crate == 'all' || github.event.inputs.crate == 'resource-types' }}
      run: |
        cd crates/resource-types
        cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      continue-on-error: true  # In case it's already published
    
    # Wait a bit for crates.io to update
    - name: Wait for resource-types to be available
      if: ${{ github.event.inputs.crate == 'all' }}
      run: sleep 30
    
    - name: Publish resource-codegen
      if: ${{ github.event.inputs.crate == 'all' || github.event.inputs.crate == 'resource-codegen' }}
      run: |
        cd crates/resource-codegen
        # Update dependency to use published version if publishing all
        if [ "${{ github.event.inputs.crate }}" = "all" ]; then
          sed -i 's/path = "..\/resource-types"/version = "0.1.0"/' Cargo.toml
        fi
        cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      continue-on-error: true  # In case it's already published
    
    # Wait for resource-codegen to be available
    - name: Wait for resource-codegen to be available
      if: ${{ github.event.inputs.crate == 'all' }}
      run: sleep 30
    
    - name: Publish protoc-gen-rust-aip
      if: ${{ github.event.inputs.crate == 'all' || github.event.inputs.crate == 'protoc-gen-rust-aip' }}
      run: |
        cd crates/protoc-gen-rust-aip
        # Update dependencies to use published versions if publishing all
        if [ "${{ github.event.inputs.crate }}" = "all" ]; then
          sed -i 's/path = "..\/resource-codegen"/version = "0.1.0"/' Cargo.toml
        fi
        cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
    
    - name: Create summary
      run: |
        echo "## Published Crates" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ github.event.inputs.crate }}" = "all" ] || [ "${{ github.event.inputs.crate }}" = "resource-types" ]; then
          echo "- ✅ [resource-types](https://crates.io/crates/resource-types)" >> $GITHUB_STEP_SUMMARY
        fi
        if [ "${{ github.event.inputs.crate }}" = "all" ] || [ "${{ github.event.inputs.crate }}" = "resource-codegen" ]; then
          echo "- ✅ [resource-codegen](https://crates.io/crates/resource-codegen)" >> $GITHUB_STEP_SUMMARY
        fi
        if [ "${{ github.event.inputs.crate }}" = "all" ] || [ "${{ github.event.inputs.crate }}" = "protoc-gen-rust-aip" ]; then
          echo "- ✅ [protoc-gen-rust-aip](https://crates.io/crates/protoc-gen-rust-aip)" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Users can now install with:" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "cargo install protoc-gen-rust-aip" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
