name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install Protocol Buffers compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install Buf
      run: |
        BUF_VERSION="1.56.0"
        curl -sSL "https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-$(uname -s)-$(uname -m)" -o buf
        chmod +x buf
        sudo mv buf /usr/local/bin/

    - name: Run checks
      run: make check

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o protoc-gen-rust-aip-linux-amd64 ./cmd/protoc-gen-rust-aip
        GOOS=linux GOARCH=arm64 go build -o protoc-gen-rust-aip-linux-arm64 ./cmd/protoc-gen-rust-aip
        GOOS=darwin GOARCH=amd64 go build -o protoc-gen-rust-aip-darwin-amd64 ./cmd/protoc-gen-rust-aip
        GOOS=darwin GOARCH=arm64 go build -o protoc-gen-rust-aip-darwin-arm64 ./cmd/protoc-gen-rust-aip
        GOOS=windows GOARCH=amd64 go build -o protoc-gen-rust-aip-windows-amd64.exe ./cmd/protoc-gen-rust-aip

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          protoc-gen-rust-aip-*
        generate_release_notes: true
